### ISSUE TITLE
How to Connect to AWS Client VPN in CI/CD Pipelines?

### ISSUE THREAD

**Issue by guilhermeabell** [samm-git/aws-vpn-client#22]
Is it possible to do the same as is done in this article? only instead of open vpn using aws client vpn?

https://semaphoreci.com/blog/connect-to-vpn-cicd-pipelines

**Comment by samm-git** [comment]
"it depends". Basically if your idp require any kind of MFA or manual actions answer is "likely not"/

**Comment by guilhermeabell** [comment]
can this help? https://docs.aws.amazon.com/mwaa/latest/userguide/tutorials-private-network-vpn-client.html

**Comment by guilhermeabell** [comment]
please, if you can help me find a solution for this, I need to run automated tests in the pipeline, and for that I would need to connect to the vpn

**Comment by guilhermeabell** [comment]
https://docs.aws.amazon.com/mwaa/latest/userguide/tutorials-docker.html

**Comment by guilhermeabell** [comment]
hello samm, what if it's SSO and not MFA?
