### ISSUE TITLE
URL redirect to https

### ISSUE THREAD

**Issue by sant123** [samm-git/aws-vpn-client#24]
Hi, I see when completing the SAML authentication it redirects to http://127.0.0.1:35001. Is it possible to redirect it to https://127.0.0.1:35001? 

Thanks!!

**Comment by s-ifti** [comment]
+1, on the same boat, Google Workspace SAML only support https.

**Comment by samm-git** [comment]
This is a local authenticator, why anyone needs https here? Also https will not work correctly as key is not trusted.

**Comment by samm-git** [comment]
Also, does it work with native client?

**Comment by samm-git** [comment]
According to [AWS Client VPN documentation](https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/federated-authentication.html#saml-config-resources) you **should** use HTTP (what does make perfect sense for localhost). So its unlikely that the configuration you provided is supported by AWS itself. It should be doable to add a self-signed cert and a TLS listener to the web server, but it will mean that the user will have to trust this certificate and to me, that flow seems to be broken anyway.

**Comment by sant123** [comment]
In my case I created a new server that uses openvpn under the hood. I wanted to upgrade it to https to add a security layer when authenticating. About the certificate I’m using mkcert to do so, the issue now is that AWS redirects to http. I tried to change the ACS to use https without success.

**Comment by samm-git** [comment]
@sant123 sorry, i still can't get why you think that "https will increase security". We are using HTTP for the localhost URL, only to capture SAML reply and sent it back to AWS as part of OpenVPN auth flow.

**Comment by sant123** [comment]
For example in public wifi networks like the airport the traffic will not be encrypted. Using https the redirect URL to the SAML entity and the redirect when authentication is success all that data will be hard to decode. That’s why https sounds good to me for this use case.

**Comment by samm-git** [comment]
@sant123 traffic to localhost never leaves your laptop, **no matter** if its public wifi or whatever else :-/

**Comment by sant123** [comment]
But the callback from the SAML entity it’s calling localhost with http. The contents in there are not encrypted, so in some way data can be exposed @samm-git don’t you think? 

My question is how that can be setup? because the bash file uses ACS::35001 as password but did not find where to specify the protocol. Unless it’s not supported /:

**Comment by samm-git** [comment]
no, it cant be exposed, as only local traffic on specific machines is using HTTP, all traffic which goes over network uses https.

**Comment by sant123** [comment]
> no, it cant be exposed, as only local traffic on specific machines is using HTTP, all traffic which goes over network uses https.

This makes sense 👌🏼 I see your point now, thank you.

**Comment by s-ifti** [comment]
I know the issue is closed, first thanks for this effort.

Regarding:

>@sant123 traffic to localhost never leaves your laptop, no matter if its public wifi or whatever else :-/

The issue is not that we care if it is https or http when invoking web request to a localhost callback, the issue is that some of the SAML provider (in this case Google Workspace) does not allow ACS URL to be plain text to begin with, hence we are not able to use Google workspace identities as VPN single singon.

This should be addressed by AWS, on searching I noticed your repo and thought this might have a chance to work with google workspace. 
I will try to change the http go lang package to use https to see if that can workout.

**Comment by samm-git** [comment]
@s-ifti my assumption that it **would** work (and btw, will not be with the official client :)) But for sure it would complain about an untrusted key, however, chrome will allow to override that. 

I think problem here is on google side. Using SAML/OIDC with http://localhost:xxxx is common approach for the local authentication, and google should do an exception here IMO.
