### ISSUE TITLE
Build patch process

### ISSUE THREAD

**Issue by javiortizmol** [samm-git/aws-vpn-client#3]
Would you please add more details about the build patch process?, because I applied the patch but When I tried to build the openvpn binary file, I got the error message: 
`rpmbuild -tb openvpn-patched.tar.gz`
error: Found more than one spec file in openvpn-patched.tar.gz

I couldn't found the configure file, trying to follow the other approach to build it.

**Comment by abdrehman98** [comment]
Hi @samm-git

Can you please help me out?

I am unable to build OpenVPN binary. 
Can you please provide me steps?

I am using LMDE5, its based on debian 11.

Thanks in advance.

**Comment by abdrehman98** [comment]
NVM

I was able to build patched OpenVPN using the following steps:

1. Download OpenVPN source code from: https://swupdate.openvpn.org/community/releases/openvpn-2.5.1.tar.gz
2. Extract the source.
3. Open a terminal in the extracted folder.
4. Apply the patch and build using the following commands: 
`patch -p1 < {path to this repo}/openvpn-v2.5.1-aws.patch && autoreconf -ivf && ./configure && make`
5. Vola you have complied successfully.
